; PlatformIO Project Configuration File
; Artoria Tamagotchi - ESP32-S3 N16R8
; Display: SSD1351 1.5" 128x128 65K Color OLED

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -std=gnu++17
    -DUSER_SETUP_LOADED=1
    -DSSD1351_DRIVER=1
    -DTFT_WIDTH=128
    -DTFT_HEIGHT=128
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_CS=10
    -DTFT_DC=8
    -DTFT_RST=9
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DSPI_FREQUENCY=20000000
build_unflags = -std=gnu++11
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1351 library
